### ISSUE TITLE
firmware for plasma printer

### ISSUE THREAD

**Issue by mkeyno** [IRNAS/GoodEnoughCNC-PlasmaCutter#3]
hi 
thanks for sharing the drawing , but I was wondering what is current cnc software status ? have you decide which platform should be developed? if so I suggested to use Marlin 3d printer firmware which is modified by[ cool guys ](https://github.com/HakanBastedt/Marlin4Due/tree/Laser)for using in laser CNC ,but I think  with some extra modification could be easily adapted for plasma cutter 
my best regards

**Comment by SloMusti** [comment]
We use http://goodenoughcnc.eu/toslink-cnc/ as the basis for control, the controller used can be either Arduino Uno with GRBL, Marlin or Planet-cnc and in fact any controller.

We will add detailed instructions on control system shortly.

**Comment by dudemeister53** [comment]
Thank you very much for this project.  I have my goodenoughcnc assembled utilizing the Toslink system and a Planet CNC controller.  I was just wondering if you can publish the planet-cnc controller settings file you are currently using.  I'm specifically looking for information on stepper motor speed control settings,

Thank you!

**Comment by SloMusti** [comment]
Settings available here: https://github.com/IRNAS/GoodEnoughCNC-PlasmaCutter/blob/master/goodenoughcnc-hybrid-planetcnc.setting
